version: "3.8"

services:
  nginx:
    image: faisalf4/setup-nginx:v1.0.0
    restart: always
    depends_on:
      - client
      - server
    ports:
      - "80:80"

  client:
    image: faisalf4/setup-client:v1.0.0
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}

  server:
    image: faisalf4/setup-server:v1.0.0
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - TOKEN_KEY=${TOKEN_KEY}
      - EMAIL=${EMAIL}
      - PASSWORD=${PASSWORD}