name: GOGO G1 ARTIFACT REGISTRY

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-server:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
    - name: code checkout
      uses: actions/checkout@v2 # Needed by default

    - name: Install node_modules
      run: cd ./setup/client | npm i
  
    - name: Run unit tests
      run: npm test

    - name: Change diretory
      run: cd ../../

    - name: Install gc-cloud-cli
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{secrets.GOOGLE_PROJECT}}
        service_account_key: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
        export_default_credentials: true

    - name: Build and push server image to artifact registry
      env: 
        GOOGLE_PROJECT: ${{secrets.GOOGLE_PROJECT}}
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev
        docker build -t us-central1-docker.pkg.dev/glass-potion-394306/gogo-g1/gogo_server:v1.0.0 ./setup/server
        docker push us-central1-docker.pkg.dev/glass-potion-394306/gogo-g1/gogo_server:v1.0.0
    
    - name: Build and push client image to artifact registry
      env: 
        GOOGLE_PROJECT: ${{secrets.GOOGLE_PROJECT}}
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev
        docker build -t us-central1-docker.pkg.dev/glass-potion-394306/gogo-g1/gogo_client:v1.0.0 ./setup/client
        docker push us-central1-docker.pkg.dev/glass-potion-394306/gogo-g1/gogo_client:v1.0.0
