name: GOGO DOCKER HUB + AWS-EB

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # From TUT

# Set environment variables
env:
  MONGODB_URI: ${{ secrets.MONGODB_URI }}
  TOKEN_KEY: ${{ secrets.TOKEN_KEY }}
  EMAIL: ${{ secrets.EMAIL }}
  PASSWORD: ${{ secrets.PASSWORD }}

jobs:
  build-server:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install client dependencies
      working-directory: ./setup/client
      run: npm install

    - name: Run unit tests
      working-directory: ./setup/client
      run: npm test
    
    - name: Install Server dependencies
      working-directory: ./setup/server
      run: |
        npm install
        export MONGODB_URI=$MONGODB_URI
        export TOKEN_KEY=$TOKEN_KEY
        export EMAIL=$EMAIL
        export PASSWORD=$PASSWORD

    - name: Build server image
      working-directory: ./setup/server
      run: docker build . --file Dockerfile --tag faisalf4/setup-server:v1.0.0
      
    - name: Build client image
      working-directory: ./setup/client
      run: docker build . --file Dockerfile --tag faisalf4/setup-client:v1.0.0
    
    - name: Build NGINX image
      working-directory: ./setup/nginx
      run: docker build . --file Dockerfile --tag faisalf4/setup-nginx:v1.0.0
      
    - name: Log into DockerHub Registry
      run: echo "${{secrets.DOCKER_PASSWORD }}" | docker login -u faisalf4 --password-stdin 

    - name: Push server image to DockerHub
      run: docker push faisalf4/setup-server:v1.0.0

    - name: Push nginx image to DockerHub
      run: docker push faisalf4/setup-nginx:v1.0.0

    - name: Push client image to DockerHub
      run: docker push faisalf4/setup-client:v1.0.0

    - name: Push server image to DockerHub Registry
      run: docker push faisalf4/setup-client:v1.0.0

    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v21 ## Predefined github ation
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: ${{ secrets.EB_APP_NAME }}
        environment_name: ${{ secrets.EB_ENV_NAME }}
        region: ${{ secrets.EB_REGION }}
        version_label: "version-${{ github.run_number }}"
        deployment_package: docker-compose.yml