name: deploy-server

on:
  push:
    branches:
      - main

jobs:

  deploy:
    name: Deploy to EC2 on main branch
    runs-on: self-hosted

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Install node modules
        run: cd /home/ec2-user/actions-runner/_work/GOGO_MERN/GOGO_MERN/setup/server && npm i
        
      - name: start gogo server
        run: cd /home/ec2-user/actions-runner/_work/GOGO_MERN/GOGO_MERN/setup/server && pm2 restart server --update-env

      - name: Restart NGINX
        run: sudo service nginx restart
      